import type { BezelInsert } from "../types";

const SKX_INSERT_HINT =
  "38 x 30.6mm sloped insert (SKX-style), also sold as 38 x 30.5mm. Fits the 42mm SKX-style and 40mm dive/GMT cases.";
const COMPACT_INSERT_HINT = "36.5 x 30.5mm insert for the 39mm vintage-diver pattern.";

export const bezelInserts: BezelInsert[] = [
  // --- 38 x 30.6mm ---
  {
    id: "insert-dive-black-alu",
    category: "bezelInsert",
    name: "Dive 60 Black (aluminium)",
    description: "Classic black aluminium 60-minute dive scale with lume pip.",
    scale: "dive-60",
    material: "aluminium",
    outerMm: 38,
    innerMm: 30.6,
    colorHex: "#16181b",
    printColorHex: "#f2f2ee",
    lumePip: true,
    costEur: 10,
    leadTimeDays: 10,
    supplierHint: SKX_INSERT_HINT,
  },
  {
    id: "insert-dive-blue-ceramic",
    category: "bezelInsert",
    name: "Dive 60 Blue (ceramic)",
    description: "Glossy blue ceramic dive scale that won't fade or scratch, with lume pip.",
    scale: "dive-60",
    material: "ceramic",
    outerMm: 38,
    innerMm: 30.6,
    colorHex: "#1d3a66",
    printColorHex: "#f0f0ea",
    lumePip: true,
    costEur: 32,
    leadTimeDays: 14,
    supplierHint: SKX_INSERT_HINT,
  },
  {
    id: "insert-gmt-blue-red-alu",
    category: "bezelInsert",
    name: "GMT 24 Blue/Red (aluminium)",
    description: "Two-tone 24-hour scale: blue and red halves separate night from day in the second zone.",
    scale: "gmt-24",
    material: "aluminium",
    outerMm: 38,
    innerMm: 30.6,
    colorHex: "#1f3f7a",
    secondaryColorHex: "#a8262c",
    printColorHex: "#f2f2ee",
    lumePip: true,
    costEur: 14,
    leadTimeDays: 10,
    supplierHint: SKX_INSERT_HINT,
  },
  {
    id: "insert-gmt-black-red-alu",
    category: "bezelInsert",
    name: "GMT 24 Black/Red (aluminium)",
    description: "Two-tone black and red 24-hour scale for reading a second time zone.",
    scale: "gmt-24",
    material: "aluminium",
    outerMm: 38,
    innerMm: 30.6,
    colorHex: "#17181a",
    secondaryColorHex: "#9e2a2b",
    printColorHex: "#f2f2ee",
    lumePip: true,
    costEur: 14,
    leadTimeDays: 10,
    supplierHint: SKX_INSERT_HINT,
  },
  {
    id: "insert-gmt-black-ceramic",
    category: "bezelInsert",
    name: "GMT 24 Black (ceramic)",
    description: "Single-colour black ceramic 24-hour scale, understated and scratch-proof.",
    scale: "gmt-24",
    material: "ceramic",
    outerMm: 38,
    innerMm: 30.6,
    colorHex: "#141517",
    printColorHex: "#e9e9e4",
    lumePip: true,
    costEur: 34,
    leadTimeDays: 14,
    supplierHint: SKX_INSERT_HINT,
  },
  {
    id: "insert-countdown-grey-alu",
    category: "bezelInsert",
    name: "Countdown Grey (aluminium)",
    description: "Numbers run 60 to 0 so you can count down to a deadline, such as a parking meter or a meeting.",
    scale: "countdown-60",
    material: "aluminium",
    outerMm: 38,
    innerMm: 30.6,
    colorHex: "#5b6068",
    printColorHex: "#f2f2ee",
    lumePip: true,
    costEur: 12,
    leadTimeDays: 10,
    supplierHint: SKX_INSERT_HINT,
  },
  {
    id: "insert-dive-green-ceramic",
    category: "bezelInsert",
    name: "Dive 60 Green (ceramic)",
    description: "Glossy forest-green ceramic dive scale with lume pip, fade- and scratch-proof.",
    scale: "dive-60",
    material: "ceramic",
    outerMm: 38,
    innerMm: 30.6,
    colorHex: "#1d4a36",
    printColorHex: "#eef0ea",
    lumePip: true,
    costEur: 32,
    leadTimeDays: 14,
    supplierHint: SKX_INSERT_HINT,
  },
  {
    id: "insert-gmt-green-black-alu",
    category: "bezelInsert",
    name: "GMT 24 Green/Black (aluminium)",
    description: "Two-tone 24-hour scale: green and black halves separate day from night in the second zone.",
    scale: "gmt-24",
    material: "aluminium",
    outerMm: 38,
    innerMm: 30.6,
    colorHex: "#17181a",
    secondaryColorHex: "#24583b",
    printColorHex: "#f2f2ee",
    lumePip: true,
    costEur: 14,
    leadTimeDays: 10,
    supplierHint: SKX_INSERT_HINT,
  },

  // --- 36.5 x 30.5mm ---
  {
    id: "insert-dive-gilt-365",
    category: "bezelInsert",
    name: "Dive 60 Gilt (aluminium, compact)",
    description: "Black aluminium dive scale with gold print, the partner to gilt dials.",
    scale: "dive-60",
    material: "aluminium",
    outerMm: 36.5,
    innerMm: 30.5,
    colorHex: "#121212",
    printColorHex: "#c9a45c",
    lumePip: true,
    costEur: 14,
    leadTimeDays: 14,
    supplierHint: COMPACT_INSERT_HINT,
  },
  {
    id: "insert-dive-burgundy-365",
    category: "bezelInsert",
    name: "Dive 60 Burgundy (aluminium, compact)",
    description: "Faded-burgundy aluminium dive scale with cream print.",
    scale: "dive-60",
    material: "aluminium",
    outerMm: 36.5,
    innerMm: 30.5,
    colorHex: "#5e1f2a",
    printColorHex: "#efe6d2",
    lumePip: true,
    costEur: 14,
    leadTimeDays: 14,
    supplierHint: COMPACT_INSERT_HINT,
  },
  {
    id: "insert-dive-black-ceramic-365",
    category: "bezelInsert",
    name: "Dive 60 Black (ceramic, compact)",
    description: "Glossy black ceramic dive scale with white print and lume pip, for the compact diver.",
    scale: "dive-60",
    material: "ceramic",
    outerMm: 36.5,
    innerMm: 30.5,
    colorHex: "#131416",
    printColorHex: "#f0f0ea",
    lumePip: true,
    costEur: 30,
    leadTimeDays: 21,
    supplierHint: `${COMPACT_INSERT_HINT} Ceramic versions come from the case maker's own insert range.`,
    dataNotes:
      "The 36.5 x 30.5mm seat is single-source (see the Compact Diver 39); confirm the maker sells this seat in ceramic, not only aluminium, before offering it.",
  },
];
