import type { WatchCase } from "../types";

/**
 * Aftermarket NH3x cases. Dial, crystal and insert seats follow the case
 * pattern each one is modelled on (see docs/parts-research.md); where a maker
 * does not publish a seat size the value is an estimate and `dataNotes` says so.
 * `handClearanceMm` is an estimate throughout: no maker publishes it.
 */
export const cases: WatchCase[] = [
  {
    id: "case-diver-42",
    category: "case",
    name: "Classic Diver 42",
    description: "42mm steel dive case, 3.8 o'clock screw-down crown, 120-click bezel, 200m.",
    style: "diver",
    material: "316L steel",
    finish: "brushed & polished",
    movementFamily: "NH3x",
    diameterMm: 42,
    lugToLugMm: 46,
    thicknessMm: 13.3,
    lugWidthMm: 22,
    crownPosition: 3.8,
    screwDownCrown: true,
    dialDiameterMm: 28.5,
    crystalDiameterMm: 31.5,
    bezel: "unidirectional-120",
    insertMm: { outer: 38, inner: 30.6 },
    chapterRing: true,
    caseback: "solid",
    waterResistanceM: 200,
    handClearanceMm: 1.8,
    costEur: 55,
    leadTimeDays: 14,
    supplierHint:
      "SKX-style aftermarket case. Takes the SKX family's 31.5mm crystals and 38 x 30.6mm sloped inserts.",
    dataNotes:
      "Sloped inserts for this pattern are sold as 38 x 30.5 or 38 x 30.6mm. Flat inserts (38 x 31.5-31.7mm) need a flat-insert bezel and are not stocked.",
  },
  {
    id: "case-diver-39",
    category: "case",
    name: "Compact Diver 39",
    description: "Vintage-proportioned 39mm diver: 3 o'clock screw-down crown, domed crystal, 120-click bezel.",
    style: "diver",
    material: "316L steel",
    finish: "brushed & polished",
    movementFamily: "NH3x",
    diameterMm: 39,
    lugToLugMm: 47,
    thicknessMm: 13.5,
    lugWidthMm: 20,
    crownPosition: 3,
    screwDownCrown: true,
    dialDiameterMm: 28.5,
    crystalDiameterMm: 30,
    bezel: "unidirectional-120",
    insertMm: { outer: 36.5, inner: 30.5 },
    chapterRing: false,
    caseback: "solid",
    waterResistanceM: 200,
    handClearanceMm: 1.9,
    costEur: 60,
    leadTimeDays: 21,
    supplierHint: "39mm vintage-diver pattern NH case. Its inserts are smaller than the 38mm SKX-style ones.",
    dataNotes:
      "Insert size is from one maker's 39mm pattern. The crystal seat is an estimate, and listed water resistance for this pattern ranges from 50 to 200m, so confirm all three with the case maker.",
  },
  {
    id: "case-field-38",
    category: "case",
    name: "Field 38",
    description: "Slim 38mm field case: smooth fixed bezel, screw-down crown at 3, 100m.",
    style: "field",
    material: "316L steel",
    finish: "brushed",
    movementFamily: "NH3x",
    diameterMm: 38,
    lugToLugMm: 45,
    thicknessMm: 11.8,
    lugWidthMm: 20,
    crownPosition: 3,
    screwDownCrown: true,
    dialDiameterMm: 28.5,
    crystalDiameterMm: 29.5,
    bezel: "fixed",
    chapterRing: false,
    caseback: "solid",
    waterResistanceM: 100,
    handClearanceMm: 1.5,
    costEur: 50,
    leadTimeDays: 14,
    supplierHint:
      "Field-pattern NH case. The dial sits on the movement's grey dial-holding spacer and the case takes 29.5mm crystals.",
    dataNotes: "Interpolated from the maker's 36mm and 39mm versions (both 28.5mm dial, 29.5mm crystal). Confirm lug-to-lug.",
  },
  {
    id: "case-dress-39",
    category: "case",
    name: "Dress 39 Exhibition",
    description: "Polished 39mm dress case with a double-domed crystal and a sapphire caseback that shows the movement.",
    style: "dress",
    material: "316L steel",
    finish: "polished",
    movementFamily: "NH3x",
    diameterMm: 39,
    lugToLugMm: 46,
    thicknessMm: 13.3,
    lugWidthMm: 20,
    crownPosition: 3,
    screwDownCrown: false,
    dialDiameterMm: 28.5,
    crystalDiameterMm: 29.5,
    bezel: "none",
    chapterRing: true,
    caseback: "display",
    waterResistanceM: 50,
    handClearanceMm: 2,
    costEur: 70,
    leadTimeDays: 21,
    supplierHint: "'GS-style' 39mm NH case with a sapphire exhibition caseback. It uses the 29.5mm crystal family.",
    dataNotes:
      "The reference case is rated 200m with a screw-down crown. This push-pull, display-back version is listed at a conservative 50m until the maker confirms.",
  },
  {
    id: "case-pilot-39",
    category: "case",
    name: "Pilot 39",
    description: "39mm pilot case with a wide 33.5mm dial opening and a slim bezel, for big legible numerals.",
    style: "pilot",
    material: "316L steel",
    finish: "bead-blasted",
    movementFamily: "NH3x",
    diameterMm: 39,
    lugToLugMm: 48.5,
    thicknessMm: 12.7,
    lugWidthMm: 20,
    crownPosition: 3,
    screwDownCrown: true,
    dialDiameterMm: 33.5,
    crystalDiameterMm: 34.5,
    bezel: "none",
    chapterRing: false,
    caseback: "solid",
    waterResistanceM: 100,
    handClearanceMm: 1.7,
    costEur: 40,
    leadTimeDays: 21,
    supplierHint: "Vintage-pilot pattern NH case for 33.5mm dials (the movement sits in a wider dial ring).",
    dataNotes:
      "The maker lists a sapphire crystal but no size, so the 34.5mm seat is an estimate. Water resistance is not published for the steel version; 100m is assumed.",
  },
  {
    id: "case-gmt-40",
    category: "case",
    name: "Travel GMT 40",
    description: "40mm case with a bidirectional 24-hour bezel and room for the NH34's four-hand stack, 200m.",
    style: "gmt",
    material: "316L steel",
    finish: "brushed & polished",
    movementFamily: "NH3x",
    diameterMm: 40,
    lugToLugMm: 47.5,
    thicknessMm: 13.5,
    lugWidthMm: 20,
    crownPosition: 3,
    screwDownCrown: true,
    dialDiameterMm: 28.5,
    crystalDiameterMm: 30.5,
    bezel: "bidirectional-24h",
    insertMm: { outer: 38, inner: 30.6 },
    chapterRing: true,
    caseback: "solid",
    waterResistanceM: 200,
    handClearanceMm: 1.9,
    costEur: 65,
    leadTimeDays: 21,
    supplierHint:
      "40mm dive/GMT-pattern NH case with a bidirectional bezel. Takes the same 38 x 30.6mm sloped inserts as SKX-style cases.",
    dataNotes: "The crystal seat (30.5mm) is an estimate because the makers found do not publish it. Confirm it before ordering spare crystals.",
  },
  {
    id: "case-field-ti-39",
    category: "case",
    name: "Titanium Field 39",
    description: "Grade 2 titanium, about 40% lighter than steel. Bead-blasted, wide 33.5mm dial, 200m.",
    style: "field",
    material: "titanium",
    finish: "bead-blasted",
    movementFamily: "NH3x",
    diameterMm: 39,
    lugToLugMm: 48.6,
    thicknessMm: 12,
    lugWidthMm: 20,
    crownPosition: 3,
    screwDownCrown: true,
    dialDiameterMm: 33.5,
    crystalDiameterMm: 34.5,
    bezel: "fixed",
    chapterRing: false,
    caseback: "solid",
    waterResistanceM: 200,
    handClearanceMm: 1.7,
    costEur: 90,
    leadTimeDays: 21,
    supplierHint: "Ti-2 pilot/field-pattern NH case for 33-34mm dials.",
    dataNotes: "The crystal seat (34.5mm) is an estimate because the maker lists sapphire without a size. Confirm it with the maker.",
  },
  {
    id: "case-diver-bronze-40",
    category: "case",
    name: "Bronze Diver 40",
    description: "CuSn8 bronze that weathers to its own patina. 120-click bezel, steel caseback, 200m.",
    style: "diver",
    material: "bronze",
    finish: "brushed",
    movementFamily: "NH3x",
    diameterMm: 40,
    lugToLugMm: 47.2,
    thicknessMm: 13.5,
    lugWidthMm: 20,
    crownPosition: 3,
    screwDownCrown: true,
    dialDiameterMm: 28.5,
    crystalDiameterMm: 30.5,
    bezel: "unidirectional-120",
    insertMm: { outer: 38, inner: 30.6 },
    chapterRing: true,
    caseback: "solid",
    waterResistanceM: 200,
    handClearanceMm: 1.8,
    costEur: 80,
    leadTimeDays: 21,
    supplierHint: "40mm CuSn8 bronze dive-pattern NH case with a stainless caseback. Takes 38 x 30.6mm inserts.",
    dataNotes:
      "The maker lists dial fit as 27.4-29.2mm, so a 28.5mm dial is used. The crystal seat (30.5mm) is an estimate shared with the 40mm GMT pattern.",
  },
  {
    id: "case-sport-pvd-42",
    category: "case",
    name: "Black Sport 42",
    description: "SKX-style case in black PVD with a fixed bezel: 3.8 o'clock screw-down crown, 200m.",
    style: "sport",
    material: "316L steel",
    finish: "PVD black",
    movementFamily: "NH3x",
    diameterMm: 42,
    lugToLugMm: 46,
    thicknessMm: 13.3,
    lugWidthMm: 22,
    crownPosition: 3.8,
    screwDownCrown: true,
    dialDiameterMm: 28.5,
    crystalDiameterMm: 31.5,
    bezel: "fixed",
    chapterRing: true,
    caseback: "solid",
    waterResistanceM: 200,
    handClearanceMm: 1.5,
    costEur: 65,
    leadTimeDays: 21,
    supplierHint: "SKX-style NH case in PVD black with a fixed bezel. It shares the 31.5mm SKX crystal family.",
    dataNotes: "Fixed-bezel versions of this pattern vary by maker. Confirm the crystal seat is the standard 31.5mm.",
  },
];
