import type { Crystal } from "../types";

/** `thicknessMm` is the overall height, including the dome for domed crystals. */
export const crystals: Crystal[] = [
  // --- 31.5mm: SKX-style cases ---
  {
    id: "crystal-sapphire-flat-315",
    category: "crystal",
    name: "Sapphire flat 31.5mm",
    description: "Flat sapphire with inner AR coating: clear and nearly scratch-proof.",
    material: "sapphire",
    shape: "flat",
    diameterMm: 31.5,
    thicknessMm: 2.9,
    arCoating: "inner",
    costEur: 20,
    leadTimeDays: 10,
    supplierHint: "SKX-family 31.5mm flat sapphire, widely stocked by mod-part shops.",
  },
  {
    id: "crystal-sapphire-dd-315",
    category: "crystal",
    name: "Sapphire double-dome 31.5mm",
    description: "Double-domed sapphire with AR on both sides: vintage distortion at the edges, no glare.",
    material: "sapphire",
    shape: "double-dome",
    diameterMm: 31.5,
    thicknessMm: 4.6,
    arCoating: "both",
    costEur: 38,
    leadTimeDays: 14,
    supplierHint: "SKX-family 31.5mm double-dome sapphire (4.5-4.7mm overall height depending on the maker).",
  },
  {
    id: "crystal-mineral-flat-315",
    category: "crystal",
    name: "Mineral flat 31.5mm",
    description: "Hardened mineral glass: the budget option, softer than sapphire.",
    material: "mineral",
    shape: "flat",
    diameterMm: 31.5,
    thicknessMm: 2.5,
    arCoating: "none",
    costEur: 8,
    leadTimeDays: 10,
    supplierHint: "OEM-style 31.5mm hardened mineral crystal for SKX-family cases.",
    dataNotes: "Thickness assumed from the OEM part. Measure before relying on it for gasket choice.",
  },

  // --- 30.5mm: 40mm dive/GMT-pattern cases ---
  {
    id: "crystal-sapphire-flat-305",
    category: "crystal",
    name: "Sapphire flat 30.5mm",
    description: "Flat sapphire with inner AR coating for the 40mm dive and GMT cases.",
    material: "sapphire",
    shape: "flat",
    diameterMm: 30.5,
    thicknessMm: 2.5,
    arCoating: "inner",
    costEur: 20,
    leadTimeDays: 14,
    supplierHint: "Usually supplied fitted to the 40mm case; spares from the case maker.",
    dataNotes: "Diameter follows the estimated crystal seat of the 40mm cases. Confirm it with the case maker.",
  },

  // --- 30.0mm: compact 39mm diver ---
  {
    id: "crystal-sapphire-domed-300",
    category: "crystal",
    name: "Sapphire domed 30mm",
    description: "Box-domed sapphire that gives the compact diver its vintage profile.",
    material: "sapphire",
    shape: "domed",
    diameterMm: 30,
    thicknessMm: 3.2,
    arCoating: "inner",
    costEur: 28,
    leadTimeDays: 14,
    supplierHint: "Usually supplied fitted to the 39mm diver case; spares from the case maker.",
    dataNotes: "Diameter follows the estimated crystal seat of the 39mm diver. Confirm it with the case maker.",
  },

  // --- 29.5mm: field and dress cases ---
  {
    id: "crystal-sapphire-flat-295",
    category: "crystal",
    name: "Sapphire flat 29.5mm",
    description: "Thin 1.5mm flat sapphire with inner AR coating, which keeps the case slim.",
    material: "sapphire",
    shape: "flat",
    diameterMm: 29.5,
    thicknessMm: 1.5,
    arCoating: "inner",
    costEur: 18,
    leadTimeDays: 10,
    supplierHint: "29.5 x 1.5mm flat sapphire used by the field- and dress-pattern NH cases.",
  },
  {
    id: "crystal-sapphire-dd-295",
    category: "crystal",
    name: "Sapphire double-dome 29.5mm",
    description: "Double-domed sapphire with AR on both sides, a soft glow for dress dials.",
    material: "sapphire",
    shape: "double-dome",
    diameterMm: 29.5,
    thicknessMm: 3,
    arCoating: "both",
    costEur: 32,
    leadTimeDays: 14,
    supplierHint: "29.5mm double-dome sapphire (1.5mm edge, 3mm overall) for the dress-pattern NH cases.",
  },

  // --- 34.5mm: wide-dial pilot and titanium field cases ---
  {
    id: "crystal-sapphire-flat-345",
    category: "crystal",
    name: "Sapphire flat 34.5mm",
    description: "Flat sapphire with inner AR coating for the wide-dial 39mm cases.",
    material: "sapphire",
    shape: "flat",
    diameterMm: 34.5,
    thicknessMm: 2,
    arCoating: "inner",
    costEur: 24,
    leadTimeDays: 14,
    supplierHint: "Usually supplied fitted to the wide-dial case; spares from the case maker.",
    dataNotes: "Diameter follows the estimated crystal seat of the wide-dial cases. Confirm it with the case maker.",
  },
  {
    id: "crystal-mineral-domed-345",
    category: "crystal",
    name: "Mineral domed 34.5mm",
    description: "Gently domed mineral glass, a lower-cost vintage look for the wide-dial cases.",
    material: "mineral",
    shape: "domed",
    diameterMm: 34.5,
    thicknessMm: 2.8,
    arCoating: "none",
    costEur: 10,
    leadTimeDays: 14,
    supplierHint: "Domed mineral crystal made to the wide-dial case's seat.",
    dataNotes: "Diameter follows the estimated crystal seat of the wide-dial cases. Confirm it with the case maker.",
  },
];
