import type { Dial } from "../types";

const SKX_FEET_HINT = "Aftermarket 28.5mm NH dial with feet set for a 3.8 o'clock crown (SKX-style cases).";
const STANDARD_FEET_HINT = "Aftermarket 28.5mm NH dial with feet set for a 3 o'clock crown.";
/** Centre holes: standard NH dials clear the hour wheel; NH34-ready GMT dials also clear the 24h wheel. */
const STANDARD_CENTER_HOLE_MM = 2.05;
const GMT_CENTER_HOLE_MM = 2.8;
const WIDE_DIAL_HINT = "33.5mm NH dial for wide-opening pilot/field cases; feet set for a 3 o'clock crown.";

export const dials: Dial[] = [
  // --- 28.5mm, 3.8 o'clock crown (SKX-style cases) ---
  {
    id: "dial-diver-black",
    category: "dial",
    name: "Diver Black",
    description: "Matte black dive dial, round lume plots, date at 3.",
    style: "diver",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3.8,
    dateWindow: "date-3",
    colorHex: "#15171a",
    printColorHex: "#f2f2ee",
    texture: "matte",
    indices: "printed",
    lume: "green",
    has24hScale: false,
    printable: true,
    costEur: 25,
    leadTimeDays: 10,
    supplierHint: SKX_FEET_HINT,
  },
  {
    id: "dial-diver-blue-daydate",
    category: "dial",
    name: "Diver Blue Day-Date",
    description: "Deep blue sunburst with applied, lumed indices and a day-date window at 3.",
    style: "diver",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3.8,
    dateWindow: "day-date-3",
    colorHex: "#1f3a5f",
    printColorHex: "#f4f4f0",
    texture: "sunburst",
    indices: "applied",
    lume: "blue",
    has24hScale: false,
    printable: false,
    costEur: 38,
    leadTimeDays: 14,
    supplierHint: SKX_FEET_HINT,
  },
  {
    id: "dial-diver-orange",
    category: "dial",
    name: "Diver Burnt Orange",
    description: "Burnt-orange sunburst dive dial with bold printed markers, date at 3.",
    style: "diver",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3.8,
    dateWindow: "date-3",
    colorHex: "#c2571f",
    printColorHex: "#f7f3ea",
    texture: "sunburst",
    indices: "printed",
    lume: "green",
    has24hScale: false,
    printable: true,
    costEur: 28,
    leadTimeDays: 10,
    supplierHint: SKX_FEET_HINT,
  },
  {
    id: "dial-sport-graphite-daydate",
    category: "dial",
    name: "Sport Graphite Day-Date",
    description: "Grained graphite dial with Arabic numerals and a day-date window at 3.",
    style: "sport",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3.8,
    dateWindow: "day-date-3",
    colorHex: "#2b2e33",
    printColorHex: "#e9ebe6",
    texture: "grained",
    indices: "arabic",
    lume: "green",
    has24hScale: false,
    printable: true,
    costEur: 30,
    leadTimeDays: 10,
    supplierHint: SKX_FEET_HINT,
  },

  // --- 28.5mm, 3 o'clock crown ---
  {
    id: "dial-diver-gilt",
    category: "dial",
    name: "Gilt Diver",
    description: "Gloss black with gold print and aged lume, no date, like a 1950s diver.",
    style: "diver",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "none",
    colorHex: "#111111",
    printColorHex: "#c9a45c",
    texture: "gloss",
    indices: "printed",
    lume: "vintage",
    has24hScale: false,
    printable: true,
    costEur: 32,
    leadTimeDays: 14,
    supplierHint: STANDARD_FEET_HINT,
  },
  {
    id: "dial-diver-teal",
    category: "dial",
    name: "Diver Teal",
    description: "Teal sunburst with applied lumed indices, date at 3.",
    style: "diver",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "date-3",
    colorHex: "#1f5f63",
    printColorHex: "#f2f2ee",
    texture: "sunburst",
    indices: "applied",
    lume: "green",
    has24hScale: false,
    printable: true,
    costEur: 34,
    leadTimeDays: 14,
    supplierHint: STANDARD_FEET_HINT,
  },
  {
    id: "dial-field-cream",
    category: "dial",
    name: "Field Cream",
    description: "Warm cream dial with a railroad track, Arabic numerals and aged lume. No date.",
    style: "field",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "none",
    colorHex: "#efe6d2",
    printColorHex: "#2a2a2a",
    texture: "matte",
    indices: "arabic",
    lume: "vintage",
    has24hScale: false,
    printable: true,
    costEur: 24,
    leadTimeDays: 10,
    supplierHint: STANDARD_FEET_HINT,
  },
  {
    id: "dial-field-olive",
    category: "dial",
    name: "Field Olive",
    description: "Matte olive field dial with cream Arabic numerals, date at 3.",
    style: "field",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "date-3",
    colorHex: "#4a5234",
    printColorHex: "#efeadb",
    texture: "matte",
    indices: "arabic",
    lume: "green",
    has24hScale: false,
    printable: true,
    costEur: 24,
    leadTimeDays: 10,
    supplierHint: STANDARD_FEET_HINT,
  },
  {
    id: "dial-field-white-daydate",
    category: "dial",
    name: "Field White Day-Date",
    description: "Crisp white dial with black Arabic numerals and a day-date window at 3.",
    style: "field",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "day-date-3",
    colorHex: "#f4f3ee",
    printColorHex: "#1c1c1c",
    texture: "matte",
    indices: "arabic",
    lume: "blue",
    has24hScale: false,
    printable: true,
    costEur: 26,
    leadTimeDays: 10,
    supplierHint: STANDARD_FEET_HINT,
  },
  {
    id: "dial-dress-silver",
    category: "dial",
    name: "Dress Silver Sunburst",
    description: "Silver sunburst with slim applied batons and no date: clean and quiet.",
    style: "dress",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "none",
    colorHex: "#d6d8d9",
    printColorHex: "#2b2b2b",
    texture: "sunburst",
    indices: "applied",
    lume: "none",
    has24hScale: false,
    printable: true,
    costEur: 36,
    leadTimeDays: 14,
    supplierHint: STANDARD_FEET_HINT,
  },
  {
    id: "dial-dress-ivory-roman",
    category: "dial",
    name: "Dress Ivory Roman",
    description: "Gloss ivory lacquer with black Roman numerals and a small date at 3.",
    style: "dress",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "date-3",
    colorHex: "#f3ecdc",
    printColorHex: "#1b1b1b",
    texture: "gloss",
    indices: "roman",
    lume: "none",
    has24hScale: false,
    printable: false,
    costEur: 34,
    leadTimeDays: 14,
    supplierHint: STANDARD_FEET_HINT,
  },
  {
    id: "dial-gmt-black",
    category: "dial",
    name: "GMT Black 24h",
    description: "Matte black with a printed 24-hour ring for the GMT hand and a wide centre hole for the NH34. Date at 3.",
    style: "gmt",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: GMT_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "date-3",
    colorHex: "#16181b",
    printColorHex: "#f2f2ee",
    texture: "matte",
    indices: "printed",
    lume: "green",
    has24hScale: true,
    printable: true,
    costEur: 32,
    leadTimeDays: 14,
    supplierHint: "NH34-ready 28.5mm GMT dial (centre hole about 2.7-2.9mm), feet set for a 3 o'clock crown.",
  },
  {
    id: "dial-gmt-blue",
    category: "dial",
    name: "GMT Blue 24h",
    description: "Blue sunburst with applied indices, a 24-hour ring and a wide centre hole for the NH34. Date at 3.",
    style: "gmt",
    movementFamily: "NH3x",
    diameterMm: 28.5,
    centerHoleMm: GMT_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "date-3",
    colorHex: "#22426b",
    printColorHex: "#f4f4f0",
    texture: "sunburst",
    indices: "applied",
    lume: "green",
    has24hScale: true,
    printable: false,
    costEur: 40,
    leadTimeDays: 14,
    supplierHint: "NH34-ready 28.5mm GMT dial (centre hole about 2.7-2.9mm), feet set for a 3 o'clock crown.",
  },

  // --- 33.5mm, 3 o'clock crown (wide-opening cases) ---
  {
    id: "dial-pilot-black",
    category: "dial",
    name: "Pilot Black",
    description: "Matte black cockpit-style dial: large Arabic numerals, triangle at 12, no date.",
    style: "pilot",
    movementFamily: "NH3x",
    diameterMm: 33.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "none",
    colorHex: "#141414",
    printColorHex: "#f5f5f0",
    texture: "matte",
    indices: "arabic",
    lume: "green",
    has24hScale: false,
    printable: true,
    costEur: 26,
    leadTimeDays: 14,
    supplierHint: WIDE_DIAL_HINT,
  },
  {
    id: "dial-pilot-slate",
    category: "dial",
    name: "Pilot Slate Date",
    description: "Grained slate-grey pilot dial with an outer minute track and date at 3.",
    style: "pilot",
    movementFamily: "NH3x",
    diameterMm: 33.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "date-3",
    colorHex: "#3c4146",
    printColorHex: "#f1f1ec",
    texture: "grained",
    indices: "arabic",
    lume: "green",
    has24hScale: false,
    printable: true,
    costEur: 28,
    leadTimeDays: 14,
    supplierHint: WIDE_DIAL_HINT,
  },
  {
    id: "dial-field-sand",
    category: "dial",
    name: "Field Sand",
    description: "Sand-coloured wide field dial with dark numerals and aged lume, date at 3.",
    style: "field",
    movementFamily: "NH3x",
    diameterMm: 33.5,
    centerHoleMm: STANDARD_CENTER_HOLE_MM,
    crownPosition: 3,
    dateWindow: "date-3",
    colorHex: "#d9c9a3",
    printColorHex: "#2c2a26",
    texture: "matte",
    indices: "arabic",
    lume: "vintage",
    has24hScale: false,
    printable: true,
    costEur: 28,
    leadTimeDays: 14,
    supplierHint: WIDE_DIAL_HINT,
  },
];
