import type { HandSet } from "../types";

/** Aftermarket NH hands are sold with 1.50 / 0.90 / 0.20mm holes; NH34 GMT hands add a 2.20mm hole. */
const NH_HOLES = { hour: 1.5, minute: 0.9, seconds: 0.2 } as const;
const NH34_HOLES = { ...NH_HOLES, gmt: 2.2 } as const;

export const hands: HandSet[] = [
  // --- Sized for 28.5mm dials (minute hand 11.5-12.5mm) ---
  {
    id: "hands-mercedes-silver",
    category: "hands",
    name: "Mercedes Silver",
    description: "Polished silver Mercedes hour hand, sword minute, lollipop seconds.",
    style: "mercedes",
    movementFamily: "NH3x",
    holesMm: { ...NH_HOLES },
    lengthsMm: { hour: 8.5, minute: 12.5, seconds: 13 },
    includesGmt: false,
    colorHex: "#d9dde2",
    secondsColorHex: "#d9dde2",
    lume: "green",
    costEur: 15,
    leadTimeDays: 10,
    supplierHint: "Aftermarket NH35 hand set for 28.5mm dials.",
  },
  {
    id: "hands-sword-silver",
    category: "hands",
    name: "Sword Silver",
    description: "Brushed silver swords with full lume and a red-tipped seconds hand.",
    style: "sword",
    movementFamily: "NH3x",
    holesMm: { ...NH_HOLES },
    lengthsMm: { hour: 8.5, minute: 12.5, seconds: 13 },
    includesGmt: false,
    colorHex: "#d4d7db",
    secondsColorHex: "#c8372d",
    lume: "green",
    costEur: 14,
    leadTimeDays: 10,
    supplierHint: "Aftermarket NH35 hand set for 28.5mm dials.",
  },
  {
    id: "hands-snowflake-gilt",
    category: "hands",
    name: "Snowflake Gilt",
    description: "Gold-tone snowflake hour hand with aged lume, a vintage diver signature.",
    style: "snowflake",
    movementFamily: "NH3x",
    holesMm: { ...NH_HOLES },
    lengthsMm: { hour: 8.5, minute: 12, seconds: 12.5 },
    includesGmt: false,
    colorHex: "#c9a45c",
    secondsColorHex: "#c9a45c",
    lume: "vintage",
    costEur: 18,
    leadTimeDays: 14,
    supplierHint: "Aftermarket NH35 hand set for 28.5mm dials.",
  },
  {
    id: "hands-dauphine-polished",
    category: "hands",
    name: "Dauphine Polished",
    description: "Faceted, mirror-polished dauphine hands with a thin seconds hand. No lume.",
    style: "dauphine",
    movementFamily: "NH3x",
    holesMm: { ...NH_HOLES },
    lengthsMm: { hour: 8, minute: 12, seconds: 12.5 },
    includesGmt: false,
    colorHex: "#e3e5e8",
    secondsColorHex: "#e3e5e8",
    lume: "none",
    costEur: 16,
    leadTimeDays: 14,
    supplierHint: "Aftermarket NH35 dress hand set for 28.5mm dials.",
  },
  {
    id: "hands-baton-black",
    category: "hands",
    name: "Baton Black",
    description: "Black-framed lumed batons with an orange seconds hand, made for dark dials.",
    style: "baton",
    movementFamily: "NH3x",
    holesMm: { ...NH_HOLES },
    lengthsMm: { hour: 8.5, minute: 12.5, seconds: 13 },
    includesGmt: false,
    colorHex: "#26282b",
    secondsColorHex: "#e0662a",
    lume: "green",
    costEur: 15,
    leadTimeDays: 10,
    supplierHint: "Aftermarket NH35 hand set for 28.5mm dials.",
  },
  {
    id: "hands-cathedral-blued",
    category: "hands",
    name: "Cathedral Blued",
    description: "Heat-blued cathedral hands with aged lume, a classic field-watch look.",
    style: "cathedral",
    movementFamily: "NH3x",
    holesMm: { ...NH_HOLES },
    lengthsMm: { hour: 8, minute: 11.5, seconds: 12.5 },
    includesGmt: false,
    colorHex: "#23395d",
    secondsColorHex: "#23395d",
    lume: "vintage",
    costEur: 18,
    leadTimeDays: 14,
    supplierHint: "Aftermarket NH35 hand set for 28.5mm dials.",
  },
  {
    id: "hands-dauphine-gold",
    category: "hands",
    name: "Dauphine Gold",
    description: "Faceted gold-tone dauphine hands with a slim gold seconds hand. No lume: for evening and dress dials.",
    style: "dauphine",
    movementFamily: "NH3x",
    holesMm: { ...NH_HOLES },
    lengthsMm: { hour: 8, minute: 12, seconds: 12.5 },
    includesGmt: false,
    colorHex: "#cfa75e",
    secondsColorHex: "#cfa75e",
    lume: "none",
    costEur: 18,
    leadTimeDays: 14,
    supplierHint: "Aftermarket NH35 dress hand set in gold tone (plated brass) for 28.5mm dials.",
  },
  {
    id: "hands-sword-blued",
    category: "hands",
    name: "Sword Blued",
    description: "Slim blued-look sword hands with a matching seconds hand. No lume: crisp on light and warm dials.",
    style: "sword",
    movementFamily: "NH3x",
    holesMm: { ...NH_HOLES },
    lengthsMm: { hour: 8.5, minute: 12, seconds: 12.5 },
    includesGmt: false,
    colorHex: "#1f3a70",
    secondsColorHex: "#1f3a70",
    lume: "none",
    costEur: 17,
    leadTimeDays: 14,
    supplierHint: "Aftermarket NH35 hand set in blue-coated steel (not flame-blued) for 28.5mm dials.",
  },
  {
    id: "hands-gmt-mercedes-red",
    category: "hands",
    name: "GMT Mercedes, Red Arrow",
    description: "Silver Mercedes set with a red arrow-tipped 24-hour hand for the NH34.",
    style: "mercedes",
    movementFamily: "NH3x",
    holesMm: { ...NH34_HOLES },
    lengthsMm: { hour: 8.5, minute: 12.5, seconds: 13, gmt: 12 },
    includesGmt: true,
    colorHex: "#d9dde2",
    secondsColorHex: "#d9dde2",
    gmtColorHex: "#c8372d",
    lume: "green",
    costEur: 26,
    leadTimeDays: 14,
    supplierHint: "Aftermarket NH34 four-hand set (GMT hand hole 2.20mm) for 28.5mm dials.",
  },
  {
    id: "hands-gmt-arrow-orange",
    category: "hands",
    name: "GMT Arrow, Orange",
    description: "Broad-arrow hour hand, sword minute and an orange 24-hour hand for the NH34.",
    style: "arrow",
    movementFamily: "NH3x",
    holesMm: { ...NH34_HOLES },
    lengthsMm: { hour: 8.5, minute: 12.5, seconds: 13, gmt: 11.5 },
    includesGmt: true,
    colorHex: "#d4d7db",
    secondsColorHex: "#e0662a",
    gmtColorHex: "#e0662a",
    lume: "green",
    costEur: 26,
    leadTimeDays: 14,
    supplierHint: "Aftermarket NH34 four-hand set (GMT hand hole 2.20mm) for 28.5mm dials.",
  },
  {
    id: "hands-gmt-sword-gilt",
    category: "hands",
    name: "GMT Sword Gilt, Yellow Arrow",
    description:
      "Gilt swords with a yellow 24-hour hand for the NH34. The short 11.5mm seconds hand clears the crystal in most cases.",
    style: "sword",
    movementFamily: "NH3x",
    holesMm: { ...NH34_HOLES },
    lengthsMm: { hour: 8.5, minute: 12.5, seconds: 11.5, gmt: 12 },
    includesGmt: true,
    colorHex: "#c9a45c",
    secondsColorHex: "#c9a45c",
    gmtColorHex: "#e8c547",
    lume: "green",
    costEur: 28,
    leadTimeDays: 14,
    supplierHint:
      "Aftermarket NH34 four-hand set (GMT hand hole 2.20mm) for 28.5mm dials, ordered with the short (under 12mm) seconds hand.",
    dataNotes:
      "Short NH34 seconds hands are sold for cases made for three-hand movements; confirm the 11.5mm length with the supplier before relying on it.",
  },

  // --- Sized for 33.5mm dials (minute hand 15-15.5mm): too long for 28.5mm dials ---
  {
    id: "hands-syringe-white-large",
    category: "hands",
    name: "Syringe White, Large",
    description: "White syringe hands with full lume, long enough for a wide pilot dial.",
    style: "syringe",
    movementFamily: "NH3x",
    holesMm: { ...NH_HOLES },
    lengthsMm: { hour: 10.5, minute: 15, seconds: 16 },
    includesGmt: false,
    colorHex: "#f1f1ec",
    secondsColorHex: "#f1f1ec",
    lume: "green",
    costEur: 16,
    leadTimeDays: 14,
    supplierHint: "NH35 hand set sized for 33.5mm dials; usually sold alongside the wide pilot dials.",
    dataNotes: "Lengths are estimated for a 33.5mm dial. Confirm them with the supplier.",
  },
  {
    id: "hands-sword-black-large",
    category: "hands",
    name: "Sword Black, Large",
    description: "Black swords with aged lume and a red seconds hand, sized for 33.5mm dials.",
    style: "sword",
    movementFamily: "NH3x",
    holesMm: { ...NH_HOLES },
    lengthsMm: { hour: 10.5, minute: 15.5, seconds: 16 },
    includesGmt: false,
    colorHex: "#1f1f1f",
    secondsColorHex: "#b8322a",
    lume: "vintage",
    costEur: 16,
    leadTimeDays: 14,
    supplierHint: "NH35 hand set sized for 33.5mm dials.",
    dataNotes: "Lengths are estimated for a 33.5mm dial. Confirm them with the supplier.",
  },
  {
    id: "hands-baton-silver-large",
    category: "hands",
    name: "Baton Silver, Large",
    description: "Polished silver batons filled with lume and a white seconds hand, sized for 33.5mm dials.",
    style: "baton",
    movementFamily: "NH3x",
    holesMm: { ...NH_HOLES },
    lengthsMm: { hour: 10.5, minute: 15.5, seconds: 16 },
    includesGmt: false,
    colorHex: "#d6d9dd",
    secondsColorHex: "#f1f1ec",
    lume: "green",
    costEur: 16,
    leadTimeDays: 14,
    supplierHint: "NH35 hand set sized for 33.5mm dials.",
    dataNotes: "Lengths are estimated for a 33.5mm dial. Confirm them with the supplier.",
  },
];
