import type { Strap } from "../types";

export const straps: Strap[] = [
  // --- 22mm ---
  {
    id: "strap-rubber-black-22",
    category: "strap",
    name: "Black rubber 22mm",
    description: "Vented FKM rubber dive strap: soft, waterproof and hard-wearing.",
    type: "rubber",
    widthMm: 22,
    colorHex: "#1b1b1b",
    costEur: 18,
    leadTimeDays: 7,
    supplierHint: "Generic 22mm FKM strap suppliers.",
  },
  {
    id: "strap-leather-brown-22",
    category: "strap",
    name: "Brown leather 22mm",
    description: "Oiled brown calf leather with contrast stitching. It softens with wear.",
    type: "leather",
    widthMm: 22,
    colorHex: "#6b4226",
    costEur: 30,
    leadTimeDays: 7,
    supplierHint: "22mm quick-release calf leather straps from strap makers.",
  },
  {
    id: "strap-nato-navy-22",
    category: "strap",
    name: "Navy NATO 22mm",
    description: "Single-pass nylon strap in navy. Light, washable and secure.",
    type: "nato",
    widthMm: 22,
    colorHex: "#1f2c44",
    costEur: 12,
    leadTimeDays: 7,
    supplierHint: "22mm nylon NATO straps.",
  },
  {
    id: "strap-bracelet-3link-22",
    category: "strap",
    name: "Three-link bracelet 22mm",
    description: "Brushed steel three-link bracelet with solid end links fitted to the Classic Diver 42.",
    type: "bracelet",
    widthMm: 22,
    colorHex: "#c9ccd0",
    compatibleCaseIds: ["case-diver-42"],
    costEur: 55,
    leadTimeDays: 14,
    supplierHint: "SKX-style 22mm bracelet with curved solid end links.",
  },
  {
    id: "strap-rubber-basket-black-22",
    category: "strap",
    name: "Black basket-weave rubber 22mm",
    description: "Supple 1960s-style perforated rubber in black: breathes in the heat and dries fast.",
    type: "rubber",
    widthMm: 22,
    colorHex: "#1c1c1c",
    costEur: 22,
    leadTimeDays: 7,
    supplierHint: "22mm tropic-style perforated rubber straps (FKM or natural rubber).",
  },
  {
    id: "strap-rubber-orange-22",
    category: "strap",
    name: "Orange rubber 22mm",
    description: "Vented FKM dive strap in bright orange, easy to spot underwater and a lift for black dials.",
    type: "rubber",
    widthMm: 22,
    colorHex: "#d9611f",
    costEur: 18,
    leadTimeDays: 7,
    supplierHint: "Generic 22mm FKM strap suppliers.",
  },

  // --- 20mm ---
  {
    id: "strap-rubber-black-20",
    category: "strap",
    name: "Black rubber 20mm",
    description: "Vented FKM rubber dive strap in 20mm.",
    type: "rubber",
    widthMm: 20,
    colorHex: "#1b1b1b",
    costEur: 18,
    leadTimeDays: 7,
    supplierHint: "Generic 20mm FKM strap suppliers.",
  },
  {
    id: "strap-rubber-navy-20",
    category: "strap",
    name: "Navy waffle rubber 20mm",
    description: "Retro waffle-pattern rubber in navy, a natural partner for vintage divers.",
    type: "rubber",
    widthMm: 20,
    colorHex: "#1f2c44",
    costEur: 22,
    leadTimeDays: 7,
    supplierHint: "20mm waffle-pattern FKM straps.",
  },
  {
    id: "strap-rubber-basket-black-20",
    category: "strap",
    name: "Black basket-weave rubber 20mm",
    description: "Supple 1960s-style perforated rubber in black, the classic partner for skin divers.",
    type: "rubber",
    widthMm: 20,
    colorHex: "#1c1c1c",
    costEur: 22,
    leadTimeDays: 7,
    supplierHint: "20mm tropic-style perforated rubber straps (FKM or natural rubber).",
  },
  {
    id: "strap-rubber-orange-20",
    category: "strap",
    name: "Orange rubber 20mm",
    description: "Vented FKM dive strap in bright orange for 20mm divers.",
    type: "rubber",
    widthMm: 20,
    colorHex: "#d9611f",
    costEur: 18,
    leadTimeDays: 7,
    supplierHint: "Generic 20mm FKM strap suppliers.",
  },
  {
    id: "strap-leather-black-20",
    category: "strap",
    name: "Black leather 20mm",
    description: "Slim black calf leather with tonal stitching, for dress watches.",
    type: "leather",
    widthMm: 20,
    colorHex: "#1a1a1a",
    costEur: 30,
    leadTimeDays: 7,
    supplierHint: "20mm quick-release calf leather straps from strap makers.",
  },
  {
    id: "strap-leather-tan-20",
    category: "strap",
    name: "Tan leather 20mm",
    description: "Tan vintage-finish leather with rivets, at home on pilot and field watches.",
    type: "leather",
    widthMm: 20,
    colorHex: "#9a6a3f",
    costEur: 30,
    leadTimeDays: 7,
    supplierHint: "20mm quick-release vintage leather straps from strap makers.",
  },
  {
    id: "strap-leather-chocolate-20",
    category: "strap",
    name: "Chocolate leather 20mm",
    description: "Smooth dark-brown calf with cream stitching: the warm partner for salmon, cream and silver dress dials.",
    type: "leather",
    widthMm: 20,
    colorHex: "#4a2f22",
    costEur: 30,
    leadTimeDays: 7,
    supplierHint: "20mm quick-release calf leather straps from strap makers.",
  },
  {
    id: "strap-leather-burgundy-20",
    category: "strap",
    name: "Burgundy leather 20mm",
    description: "Burgundy calf with cream stitching, rich against cream, white and silver dials.",
    type: "leather",
    widthMm: 20,
    colorHex: "#5b1f29",
    costEur: 32,
    leadTimeDays: 7,
    supplierHint: "20mm quick-release calf leather straps from strap makers.",
  },
  {
    id: "strap-leather-green-20",
    category: "strap",
    name: "Forest green leather 20mm",
    description: "Deep green calf with cream stitching, at home on field and pilot watches.",
    type: "leather",
    widthMm: 20,
    colorHex: "#2f4a37",
    costEur: 32,
    leadTimeDays: 7,
    supplierHint: "20mm quick-release calf leather straps from strap makers.",
  },
  {
    id: "strap-suede-grey-20",
    category: "strap",
    name: "Grey suede 20mm",
    description: "Soft grey suede with contrast stitching: relaxed, light and good with smaller cases.",
    type: "leather",
    widthMm: 20,
    colorHex: "#8b8781",
    costEur: 28,
    leadTimeDays: 7,
    supplierHint: "20mm quick-release suede straps from strap makers.",
  },
  {
    id: "strap-nato-olive-20",
    category: "strap",
    name: "Olive NATO 20mm",
    description: "Single-pass nylon strap in olive drab.",
    type: "nato",
    widthMm: 20,
    colorHex: "#4b5320",
    costEur: 12,
    leadTimeDays: 7,
    supplierHint: "20mm nylon NATO straps.",
  },
  {
    id: "strap-canvas-khaki-20",
    category: "strap",
    name: "Khaki canvas 20mm",
    description: "Waxed khaki canvas with a leather lining. Rugged, and it breaks in fast.",
    type: "canvas",
    widthMm: 20,
    colorHex: "#a89a73",
    costEur: 20,
    leadTimeDays: 7,
    supplierHint: "20mm quick-release canvas straps.",
  },
  {
    id: "strap-bracelet-3link-20",
    category: "strap",
    name: "Three-link bracelet 20mm",
    description: "Brushed three-link bracelet that tapers to the clasp, fitted to the Compact Diver 39.",
    type: "bracelet",
    widthMm: 20,
    colorHex: "#c9ccd0",
    compatibleCaseIds: ["case-diver-39"],
    costEur: 50,
    leadTimeDays: 14,
    supplierHint: "Usually sold with the 39mm diver case as a matched set with solid end links.",
  },
  {
    id: "strap-bracelet-5link-20",
    category: "strap",
    name: "Five-link bracelet 20mm",
    description: "Polished and brushed five-link bracelet fitted to the Travel GMT 40.",
    type: "bracelet",
    widthMm: 20,
    colorHex: "#cfd2d6",
    compatibleCaseIds: ["case-gmt-40"],
    costEur: 55,
    leadTimeDays: 14,
    supplierHint: "Usually sold with the 40mm GMT case as a matched set with solid end links.",
  },
  {
    id: "strap-bracelet-ti-20",
    category: "strap",
    name: "Titanium bracelet 20mm",
    description: "Light bead-blasted titanium bracelet with straight end links that fit any 20mm case.",
    type: "bracelet",
    widthMm: 20,
    colorHex: "#a9acae",
    costEur: 70,
    leadTimeDays: 14,
    supplierHint: "20mm straight-end titanium bracelet with spring-bar holes.",
  },
];
